version: '3'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    networks:
      - doublet-network
  api-gateway:
    image: tandev2k/api-gateway
    ports:
      - "80:5000"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - doublet-network
  auth-service:
    image: tandev2k/auth-service
    ports:
      - "10000:10000"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - doublet-network
    depends_on:
      - redis
  user-service:
    image: tandev2k/user-service
    ports:
      - "40000:40000"
    networks:
      - doublet-network
  product-service:
    image: tandev2k/product-service
    ports:
      - "30000:30000"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - doublet-network
  order-service:
    image: tandev2k/order-service
    ports:
      - "50000:50000"
    networks:
      - doublet-network
  recommendation-service:
    image: tandev2k/recommendation-service
    ports:
      - "15000:15000"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - doublet-network
networks:
  doublet-network:
    external: 
      name: doublet-network
